parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../app/'
        exclude:
            - '../app/DependencyInjection/'
            - '../app/Entity/'
            - '../app/Kernel.php'

    Iteo\Customer\Application\Command\CreateCustomer\CreateCustomerHandler: ~

    Iteo\Customer\Domain\CustomerRepository: ~
    Iteo\Customer\Domain\CustomerState\CustomerStateRepository: '@App\Repository\CustomerEntityRepository'

    Iteo\Shared\DomainEvent\DomainEventsDispatcher: ~
