parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../app/'
    exclude:
      - '../app/DependencyInjection/'
      - '../app/Entity/'
      - '../app/Kernel.php'

  App\Adapters\Http\Controller\:
    resource: '../app/Adapters/Http/Controller/'
    tags: [ 'controller.service_arguments' ]

  adapters_queue:
    namespace: Iteo\
    resource: '../src/**/Adapters/Queue'

  specification:
    namespace: Iteo\
    resource: '../src/**/Domain/Specification/*'

  persistence:
    namespace: Iteo\
    resource: '../src/**/Domain/Persistence/*'

  infrastructure:
    namespace: Iteo\
    resource: '../src/**/Infrastructure/*'

  handlers:
    namespace: Iteo\
    resource: '../src/**/Application/**/*Handler.php'

  Iteo\Client\Ports\Summary\GetSummary: '@App\Infrastructure\Client\ORMGetSummary'

  Iteo\Shared\DomainEvent\DomainEventsDispatcher: '@App\Infrastructure\Shared\SymfonyDomainEventsDispatcher'
  Iteo\Shared\Queue\QueueBus: '@App\Infrastructure\Framework\MessengerQueueBus'
  Iteo\Shared\CommandBus: '@App\Infrastructure\Framework\MessengerCommandBus'
