parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../app/'
    exclude:
      - '../app/DependencyInjection/'
      - '../app/Entity/'
      - '../app/Kernel.php'

  App\Controller\:
    resource: '../app/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Request\CreateClientRequestValueResolver:
    tags:
      - controller.argument_value_resolver:
          name: create_client
          priority: 150

  Iteo\Customer\Application\Command\CreateCustomer\CreateCustomerHandler: ~
  Iteo\Customer\Application\Command\PlaceOrder\PlaceOrderHandler: ~

  Iteo\Customer\Domain\Persistence\CustomerRepository: ~
  Iteo\Customer\Domain\Persistence\CustomerStateRepository: '@App\Repository\CustomerEntityRepository'

  Iteo\Shared\DomainEvent\DomainEventsDispatcher: ~

  Iteo\Customer\Domain\Specification\CustomerIdWasUsed: '@App\Customer\ORMCustomerIdWasUsed'
  Iteo\Customer\Domain\Specification\OrderIdWasUsed: '@App\Customer\ORMOrderIdWasUsed'
