parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../app/'
    exclude:
      - '../app/DependencyInjection/'
      - '../app/Entity/'
      - '../app/Kernel.php'

  App\Controller\:
    resource: '../app/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Request\CreateClientRequestValueResolver:
    tags:
      - controller.argument_value_resolver:
          name: create_client
          priority: 150

  Iteo\Shared\DomainEvent\DomainEventsDispatcher: ~

  Iteo\Client\Application\Command\CreateClient\CreateClientHandler: ~
  Iteo\Client\Application\Command\PlaceOrder\PlaceOrderHandler: ~
  Iteo\Client\Application\Command\BlockClient\BlockClientHandler: ~
  Iteo\Client\Application\Command\TopUpClient\TopUpClientHandler: ~

  Iteo\Client\Domain\Specification\ClientIdWasUsed: '@App\Client\ORMClientIdWasUsed'
  Iteo\Client\Domain\Specification\OrderIdWasUsed: '@App\Client\ORMOrderIdWasUsed'

  Iteo\Client\Domain\Persistence\ClientRepository: ~
  Iteo\Client\Domain\Persistence\ClientStateRepository: '@App\Repository\ClientEntityRepository'
