parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../app/'
    exclude:
      - '../app/DependencyInjection/'
      - '../app/Entity/'
      - '../app/Kernel.php'

  App\Adapters\Http\Controller\:
    resource: '../app/Adapters/Http/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Adapters\Http\Request\CreateClientRequestValueResolver:
    tags:
      - controller.argument_value_resolver:
          name: create_client
          priority: 150

  Iteo\Shared\DomainEvent\DomainEventsDispatcher: '@App\Infrastructure\Shared\SymfonyDomainEventsDispatcher'

  Iteo\Client\Application\CreateClient\CreateClientHandler: ~
  Iteo\Client\Application\PlaceOrder\PlaceOrderHandler: ~
  Iteo\Client\Application\BlockClient\BlockClientHandler: ~
  Iteo\Client\Application\TopUpClient\TopUpClientHandler: ~

  Iteo\Client\Domain\Specification\ClientIdWasUsed: '@App\Infrastructure\Client\ORMClientIdWasUsed'
  Iteo\Client\Domain\Specification\OrderIdWasUsed: '@App\Infrastructure\Client\ORMOrderIdWasUsed'

  Iteo\Client\Domain\Persistence\ClientRepository: ~
  Iteo\Client\Domain\Persistence\ClientStateRepository: '@App\Infrastructure\Framework\ORM\Repository\ClientEntityRepository'
